name: mongo-sharding-repl-cache

services:
  #сервер конфигурации
  configSrv:
    image: mongo:latest # docker образ
    container_name: configSrv 
    restart: always
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",  #запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #1-й шард 
  shard1_1:
    image: mongo:latest
    container_name: shard1_1
    restart: always
    volumes:
      - shard1_1-data:/data/db
    command:
      [
        "--shardsvr",     #запуск в режиме шардинга
        "--replSet",
        "shard1",         #название реплики
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  shard1_2:
    image: mongo:latest
    container_name: shard1_2
    restart: always
    volumes:
      - shard1_2-data:/data/db
    command:
      [
        "--shardsvr",     #запуск в режиме шардинга
        "--replSet",
        "shard1",         #название реплики
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  shard1_3:
    image: mongo:latest
    container_name: shard1_3
    restart: always
    volumes:
      - shard1_3-data:/data/db
    command:
      [
        "--shardsvr",     #запуск в режиме шардинга
        "--replSet",
        "shard1",         #название реплики
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  #2-й шард 
  shard2_1:
    image: mongo:latest
    container_name: shard2_1
    restart: always
    volumes:
      - shard2_1-data:/data/db
    command:
      [
        "--shardsvr",     #запуск в режиме шардинга
        "--replSet",
        "shard2",         #название реплики, обратите внимание - она отличается от реплики 1-го шарда
        "--bind_ip_all", 
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  shard2_2:
    image: mongo:latest
    container_name: shard2_2
    restart: always
    volumes:
      - shard2_2-data:/data/db
    command:
      [
        "--shardsvr",     #запуск в режиме шардинга
        "--replSet",
        "shard2",         #название реплики, обратите внимание - она отличается от реплики 1-го шарда
        "--bind_ip_all", 
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  shard2_3:
    image: mongo:latest
    container_name: shard2_3
    restart: always
    volumes:
      - shard2_3-data:/data/db
    command:
      [
        "--shardsvr",     #запуск в режиме шардинга
        "--replSet",
        "shard2",         #название реплики, обратите внимание - она отличается от реплики 1-го шарда
        "--bind_ip_all", 
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  #роутер
  router:
    image: mongo:latest
    container_name: router
    restart: always
    command:
      [
        "mongos", #обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv:27017", #передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  redis:
    image: "redis:latest"
    container_name: redis
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - router
      - redis
    ports:
      - 8090:8080
    environment:
      MONGODB_URL: "mongodb://router"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379" 

volumes:
  config-data:
  shard1_1-data:
  shard1_2-data:
  shard1_3-data:
  shard2_1-data:
  shard2_2-data:
  shard2_3-data:
  redis_data: